### PR TITLE
Rename message to action

### PR DESCRIPTION
**Pull request by brianteeman**
Its not an email manager but an action manager

### CODE REVIEW

**Comment by joomdonation** [comment]
Since we change "Message" to "Action", should we change the language keys as well, like:

COM_ACTIONLOGS_ACTION="Action"
COM_ACTIONLOGS_ACTION_ASC="Action ascending"
COM_ACTIONLOGS_ACTION_DESC="Action descending"

If we do that, we have to modify code to use new language keys, but that should be easy

**Comment by brianteeman** [comment]
I was still thinking in the mindset that this was existing cod e so I couldn't change that. You are correct and I will make the relevant changes.

**Comment by brianteeman** [comment]
Constants renamed now as well

**Comment by joomdonation** [comment]
Thanks, it's good now

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
