### PR TITLE
Improvements

### PR DESCRIPTION
**Pull request by joomdonation**
Pull Request for Issue # .

### Summary of Changes
This PR makes massive changes to current User Action logs code base. It contains following improvements:
- Added link to the user account performs the action and link to the item being changed by the action
- Store action related data in better format so that it can be used to generate the log message.
- Move the code which translates the json-encoded message to human readable message to a helper method instead of in a plugin trigger like before.
- Addressed an issue with the current implement: When we change state of multiple items, multiple records will be logged(each record for one item) but only one email sent.

There are still work left to get this PR completed, however, I want to submit it here to see whether we want to go with this direction or not before working further on it

- Update installation SQL 
- Update update SQL
- Added missing language items for other content types

action_logs

As this makes change to SQL, if someone wants to play with it, please get and install a copy of my branch https://github.com/joomdonation/privacy-framework/archive/improvements.zip

### CODE REVIEW

**Comment by brianteeman** [comment]
if i understand this correctly in order for the nice strings then they need to be added for all components into the en-GB.plg_system_userlogs.ini file.

That would seem to require a lot of duplication to me AND how would an extension be able to add the required strings

**Comment by joomdonation** [comment]
Yes. Basically, for each type of object (article, category....), we will require 6 languages items (look at articles as a sample)

A custom extension, in my mind, should implement a custom plugin with it's own language file. Unfortunately, I could not find a simpler way to support this improvements without requiring extra language items.

**Comment by brianteeman** [comment]
> Addressed an issue with the current implement: When we change state of multiple items, multiple records will be logged(each record for one item) but only one email sent.

This was by design - you would not want to receive 100 emails

**Comment by joomdonation** [comment]
Sorry, I was not clear on this. Before making this change, if you publish 100 items, there will be only one record logged and only one email. As you mentioned somewhere, we should have 100 records but only one email and this change allow it works exactly like that

**Comment by brianteeman** [comment]
> A custom extension, in my mind, should implement a custom plugin with it's own language file. Unfortunately, I could not find a simpler way to support this improvements without requiring extra language items.

is that even possible? and if it is then it seems a very inefficient option.

**Comment by alikon** [comment]
i've played a little bit with you branch  and it seems to me that with this pr we are moving in a good direction, surely better than before.
So i invite you to go on and complete this pr, so we can move togheter with the next natural step 
that you have already pointed out https://github.com/joomla-projects/privacy-framework/issues/31

**Comment by joomdonation** [comment]
Thanks. One problem with this PR is it requires more language items than it should and it will require more time for translators to do the translation to different languages. I am thinking about adding some code to component helper class to get link to resources/content types (articles, categories...) and with that approach, we can reduce the language items required. I will post the post the code when I have it ready (guess I will have time to work on this tonight my time, will post it here when it's ready so that you can have a look)

**Comment by alikon** [comment]
any enhancement is warmly welcomed...translators will be grateful to you

**Comment by joomdonation** [comment]
OK. See https://github.com/joomla-projects/privacy-framework/pull/36/ for alternative

**Comment by joomdonation** [comment]
OK @alikon. We will go with https://github.com/joomla-projects/privacy-framework/pull/36 since it's require less translation (and can avoid mistakes from translator). I'm closing this one and continue working on https://github.com/joomla-projects/privacy-framework/pull/36

**Pull request closed without merging**
