### PR TITLE
[plugin][privacyconsent] - open the privacy policy article

### PR DESCRIPTION
**Pull request by alikon**
### Summary of Changes
added a pseudo task

### Testing Instructions

- set a privacy policy article in the plugin privacyconsent
- create a new user
- log for the first time

click on the privacy policy article link
screenshot from 2018-06-17 10-15-47
### Expected result
 the privacy policy article open in  modal window

### Actual result
the user profile page is opened in modal window
screenshot from 2018-06-17 10-20-08

### CODE REVIEW

**Comment by brianteeman** [comment]
I agree that there is a bug but I dont understand why

This should work the same as the TOS field in the user profile plugin and there is no task there

**Comment by joomdonation** [comment]
This is honestly, not a good fix. I think we will have to change the code to something like that:
```php
$option           = $this->app->input->getCmd('option');
$task             = $this->app->input->get('task');
$view             = $this->app->input->getString('view', '');
$layout           = $this->app->input->getString('layout', '');
$id               = $this->app->input->getInt('id');
$privacyArticleId = $this->params->get('privacy_article');

// If user is already on edit profile screen or view privacy article or press update button, do nothing to avoid infinite redirect
if ($task == 'profile.save'
	|| ($option == 'com_content' && $view == 'article' && $id == $privacyArticleId)
	|| ($option == 'com_users' && $view == 'profile' && $layout == 'edit'))
{
	return;
}
```

Also, we have to care about multilingual website, too. So $privacyArticleId must be changed to the associated article in in the current language...

**Comment by brianteeman** [comment]
I cannot replicate this

The link that I have in the code when this plugin is enabled is
`<a href="/privacy-framework/index.php/2-uncategorised/1-abc?tmpl=component&amp;lang=*" class="modal" rel="{handler: 'iframe', size: {x:800, y:500}}">Privacy Policy</a>`

As you can see the link is using tmpl=component so there is no way for any modules to be loaded

**Comment by brianteeman** [comment]
@alikon can you still replicate this?

**Comment by joomdonation** [comment]
This should still be a valid bug. You will need to login using a new account (has not consented privacy policy yet) and you should see the bug

**Comment by brianteeman** [comment]
Ah in that one scenario it is a bug - the link is the same but on the edit profile page it is not using the tmpl=components

**Comment by alikon** [comment]
yes without  this pr i still have the issue

**Comment by joomdonation** [comment]
It's not problem with tmpl=components. It's the code which we block users from accessing to any other page before they consent privacy policy causing this bug. I will make a new PR to replace this one

**Comment by brianteeman** [comment]
@joomdonation that makes sense!!!

Thanks

**Comment by alikon** [comment]
why this is not a good fix ?

**Comment by joomdonation** [comment]
@alikon Someone can simply insert task=privacymodal to an URL (for example, URL of an article) to bypass this check

**Comment by brianteeman** [comment]
We didn't see it in core before where this same url block is used (reset password required) because the tos plugin isnt enabled on the edit profile page

**Comment by brianteeman** [comment]
Closing as I merged #117 

Thanks everyone

**Pull request closed without merging**
