### PR TITLE
Help buttons

### PR DESCRIPTION
**Pull request by brianteeman**
Adds help buttons to the components

Do we need to set them up on the help server as well? If so then I dont know how

### CODE REVIEW

**Comment by mbabker** [comment]
> Do we need to set them up on the help server as well? If so then I dont know how

Sooner or later pages have to be made on the docs wiki for them all, but the keys all look right so we should be good here.

**Comment by brianteeman** [comment]
Thanks

PS I was going to set them up for the plugins as well but ALL plugins have the same helps screen :(

**Comment by Sandra97** [comment]
@brianteeman It seems that the Help Screens for the 2 Options pages are missing. 
```
JHELP_COMPONENT_USER_ACTIONLOGS_OPTIONS="Components_User_Actionlogs_Options"
JHELP_COMPONENT_PRIVACY_OPTIONS="Components_Privacy_Options"
```

**Comment by brianteeman** [comment]
Thanks - I will fix that shortly

**Comment by Sandra97** [comment]
Another thing: 
`JHELP_COMPONENTS_PRIVACY_REQUEST_EDIT="Components_Privacy_Request_Edit"`
I can't find where it is supposed to be displayed.
When you open a request, it's calling the `JHELP_COMPONENTS_PRIVACY_REQUEST` help screen. So no idea where is the `EDIT` one

**Comment by mbabker** [comment]
That one's when you create a new request.  Mildly confusing by the name alone since the edit layout is actually only ever used to create new requests, but it follows the MVC convention used everywhere else (you're actually on the edit layout when creating new articles too)

**Comment by brianteeman** [comment]
yeah i just followed the existing convention - good or bad

**Comment by Sandra97** [comment]
Thanks.

**Comment by Sandra97** [comment]
Help Screens created. All tested except the 2 'options' one. They work as expected in the backend.
[3.9 Help Screen list](https://docs.joomla.org/Category:Help_screen_3.9)

**Comment by brianteeman** [comment]
The options were merged here #119

**Pull request merged**
